name: "워크북 미션"
description: 워크북 미션 작업 사항을 작성해주세요.
title: "[ Week ] "
body:
  - type: markdown
    attributes:
      value: |
        작성 예시 : "[ Week 1 ] 1주차 워크북 미션"
  - type: textarea
    id: feat-description
    attributes:
      label: 🛠 Mission
      description: 어떠한 미션을 수행하시는 건지 작성해주세요.
      placeholder: 설명을 작성해주세요.
    validations:
      required: true
  - type: textarea
    id: feat-list
    attributes:
      label: 📝 To-do
      description: 미션에 필요한 목록을 작성해주세요.
      placeholder: 목록을 작성해주세요.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 🔍 접근 방법
      description: 고려하신 방법이나, 접근에 대해서 설명해주세요.
      placeholder: 설명을 작성해주세요.
    validations:
      required: true
